/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Badge {
  'id' : string,
  'name' : string,
  'unlocked' : boolean,
  'description' : string,
}
export interface CapsuleMessage {
  'id' : string,
  'unlockAt' : bigint,
  'receiverId' : string,
  'timestamp' : bigint,
  'blobId' : string,
  'isUnlocked' : boolean,
  'senderId' : string,
}
export interface ConnectionRequest {
  'id' : string,
  'status' : ConnectionStatus,
  'createdAt' : bigint,
  'toUser' : string,
  'fromUser' : string,
}
export type ConnectionStatus = { 'pending' : null } |
  { 'accepted' : null } |
  { 'declined' : null };
export interface GroupInfo {
  'id' : string,
  'members' : Array<string>,
  'name' : string,
  'createdAt' : bigint,
  'createdBy' : string,
}
export interface GroupMessage {
  'id' : string,
  'content' : string,
  'senderUsername' : string,
  'isSnap' : boolean,
  'groupId' : string,
  'timestamp' : bigint,
  'snapBlobId' : [] | [string],
}
export interface LeaderboardEntry {
  'username' : string,
  'displayName' : string,
  'rank' : bigint,
  'snapScore' : bigint,
}
export interface Message {
  'id' : string,
  'content' : string,
  'isRead' : boolean,
  'isSnap' : boolean,
  'isEphemeral' : boolean,
  'receiverId' : string,
  'timestamp' : bigint,
  'snapBlobId' : [] | [string],
  'senderId' : string,
  'snapViewed' : boolean,
}
export interface Reaction {
  'username' : string,
  'emoji' : string,
  'timestamp' : bigint,
}
export interface Story {
  'id' : string,
  'authorUsername' : string,
  'expiresAt' : bigint,
  'timestamp' : bigint,
  'caption' : string,
  'blobId' : string,
  'authorDisplayName' : string,
}
export interface UserProfile {
  'bio' : string,
  'username' : string,
  'displayName' : string,
  'createdAt' : bigint,
  'principalText' : string,
  'passwordHash' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addReaction' : ActorMethod<
    [string, string, string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'clearAllData' : ActorMethod<[], { 'ok' : null }>,
  'createGroup' : ActorMethod<
    [string, string, Array<string>],
    { 'ok' : GroupInfo } |
      { 'err' : string }
  >,
  'deleteStory' : ActorMethod<
    [string, string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'getAchievements' : ActorMethod<[string], Array<Badge>>,
  'getAllUsers' : ActorMethod<[], Array<UserProfile>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCapsuleMessages' : ActorMethod<[string, string], Array<CapsuleMessage>>,
  'getCapsuleStatus' : ActorMethod<[string, string], [] | [CapsuleMessage]>,
  'getConversations' : ActorMethod<
    [string],
    Array<
      {
        'lastMessageContent' : string,
        'lastMessageTimestamp' : bigint,
        'username' : string,
        'displayName' : string,
        'unreadCount' : bigint,
      }
    >
  >,
  'getFriendStories' : ActorMethod<[string], Array<Story>>,
  'getFriends' : ActorMethod<[string], Array<UserProfile>>,
  'getGroupMessages' : ActorMethod<
    [string, string, bigint],
    Array<GroupMessage>
  >,
  'getGroups' : ActorMethod<[string], Array<GroupInfo>>,
  'getLeaderboard' : ActorMethod<[string], Array<LeaderboardEntry>>,
  'getMessages' : ActorMethod<[string, string, bigint], Array<Message>>,
  'getPendingRequestCount' : ActorMethod<[string], bigint>,
  'getPendingRequests' : ActorMethod<[string], Array<ConnectionRequest>>,
  'getProfile' : ActorMethod<[string], [] | [UserProfile]>,
  'getReactions' : ActorMethod<[string], Array<Reaction>>,
  'getReadReceiptsEnabled' : ActorMethod<[string], boolean>,
  'getSentRequests' : ActorMethod<[string], Array<ConnectionRequest>>,
  'getSnapScore' : ActorMethod<[string], bigint>,
  'getStreak' : ActorMethod<[string, string], bigint>,
  'getUnreadCount' : ActorMethod<[string], bigint>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isGhostMode' : ActorMethod<[string], boolean>,
  'login' : ActorMethod<
    [string, string],
    { 'ok' : UserProfile } |
      { 'err' : string }
  >,
  'loginWithII' : ActorMethod<[], { 'ok' : UserProfile } | { 'err' : string }>,
  'markMessageRead' : ActorMethod<
    [string, string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'postStory' : ActorMethod<
    [string, string, string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'recordDailyLogin' : ActorMethod<[string], bigint>,
  'register' : ActorMethod<
    [string, string, string],
    { 'ok' : UserProfile } |
      { 'err' : string }
  >,
  'registerWithII' : ActorMethod<
    [string, string],
    { 'ok' : UserProfile } |
      { 'err' : string }
  >,
  'respondToRequest' : ActorMethod<
    [string, string, boolean],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'searchUsers' : ActorMethod<[string], Array<UserProfile>>,
  'sendCapsuleSnap' : ActorMethod<
    [string, string, string, bigint],
    { 'ok' : CapsuleMessage } |
      { 'err' : string }
  >,
  'sendConnectionRequest' : ActorMethod<
    [string, string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'sendGroupMessage' : ActorMethod<
    [string, string, string],
    { 'ok' : GroupMessage } |
      { 'err' : string }
  >,
  'sendMessage' : ActorMethod<
    [string, string, string],
    { 'ok' : Message } |
      { 'err' : string }
  >,
  'sendSnap' : ActorMethod<
    [string, string, string, boolean, boolean],
    { 'ok' : Message } |
      { 'err' : string }
  >,
  'setGhostMode' : ActorMethod<
    [string, boolean],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'setReadReceiptsEnabled' : ActorMethod<
    [string, boolean],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'updateProfile' : ActorMethod<
    [string, string, string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'viewSnap' : ActorMethod<
    [string, string],
    { 'ok' : null } |
      { 'err' : string }
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];