/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const GroupInfo = IDL.Record({
  'id' : IDL.Text,
  'members' : IDL.Vec(IDL.Text),
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'createdBy' : IDL.Text,
});
export const Badge = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'unlocked' : IDL.Bool,
  'description' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'bio' : IDL.Text,
  'username' : IDL.Text,
  'displayName' : IDL.Text,
  'createdAt' : IDL.Int,
  'principalText' : IDL.Text,
  'passwordHash' : IDL.Text,
});
export const CapsuleMessage = IDL.Record({
  'id' : IDL.Text,
  'unlockAt' : IDL.Int,
  'receiverId' : IDL.Text,
  'timestamp' : IDL.Int,
  'blobId' : IDL.Text,
  'isUnlocked' : IDL.Bool,
  'senderId' : IDL.Text,
});
export const Story = IDL.Record({
  'id' : IDL.Text,
  'authorUsername' : IDL.Text,
  'expiresAt' : IDL.Int,
  'timestamp' : IDL.Int,
  'caption' : IDL.Text,
  'blobId' : IDL.Text,
  'authorDisplayName' : IDL.Text,
});
export const GroupMessage = IDL.Record({
  'id' : IDL.Text,
  'content' : IDL.Text,
  'senderUsername' : IDL.Text,
  'isSnap' : IDL.Bool,
  'groupId' : IDL.Text,
  'timestamp' : IDL.Int,
  'snapBlobId' : IDL.Opt(IDL.Text),
});
export const LeaderboardEntry = IDL.Record({
  'username' : IDL.Text,
  'displayName' : IDL.Text,
  'rank' : IDL.Nat,
  'snapScore' : IDL.Nat,
});
export const Message = IDL.Record({
  'id' : IDL.Text,
  'content' : IDL.Text,
  'isRead' : IDL.Bool,
  'isSnap' : IDL.Bool,
  'isEphemeral' : IDL.Bool,
  'receiverId' : IDL.Text,
  'timestamp' : IDL.Int,
  'snapBlobId' : IDL.Opt(IDL.Text),
  'senderId' : IDL.Text,
  'snapViewed' : IDL.Bool,
});
export const ConnectionStatus = IDL.Variant({
  'pending' : IDL.Null,
  'accepted' : IDL.Null,
  'declined' : IDL.Null,
});
export const ConnectionRequest = IDL.Record({
  'id' : IDL.Text,
  'status' : ConnectionStatus,
  'createdAt' : IDL.Int,
  'toUser' : IDL.Text,
  'fromUser' : IDL.Text,
});
export const Reaction = IDL.Record({
  'username' : IDL.Text,
  'emoji' : IDL.Text,
  'timestamp' : IDL.Int,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addReaction' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'clearAllData' : IDL.Func([], [IDL.Variant({ 'ok' : IDL.Null })], []),
  'createGroup' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Vec(IDL.Text)],
      [IDL.Variant({ 'ok' : GroupInfo, 'err' : IDL.Text })],
      [],
    ),
  'deleteStory' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'getAchievements' : IDL.Func([IDL.Text], [IDL.Vec(Badge)], ['query']),
  'getAllUsers' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCapsuleMessages' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Vec(CapsuleMessage)],
      [],
    ),
  'getCapsuleStatus' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Opt(CapsuleMessage)],
      ['query'],
    ),
  'getConversations' : IDL.Func(
      [IDL.Text],
      [
        IDL.Vec(
          IDL.Record({
            'lastMessageContent' : IDL.Text,
            'lastMessageTimestamp' : IDL.Int,
            'username' : IDL.Text,
            'displayName' : IDL.Text,
            'unreadCount' : IDL.Nat,
          })
        ),
      ],
      [],
    ),
  'getFriendStories' : IDL.Func([IDL.Text], [IDL.Vec(Story)], []),
  'getFriends' : IDL.Func([IDL.Text], [IDL.Vec(UserProfile)], []),
  'getGroupMessages' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Int],
      [IDL.Vec(GroupMessage)],
      [],
    ),
  'getGroups' : IDL.Func([IDL.Text], [IDL.Vec(GroupInfo)], []),
  'getLeaderboard' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(LeaderboardEntry)],
      ['query'],
    ),
  'getMessages' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Int],
      [IDL.Vec(Message)],
      [],
    ),
  'getPendingRequestCount' : IDL.Func([IDL.Text], [IDL.Nat], []),
  'getPendingRequests' : IDL.Func([IDL.Text], [IDL.Vec(ConnectionRequest)], []),
  'getProfile' : IDL.Func([IDL.Text], [IDL.Opt(UserProfile)], ['query']),
  'getReactions' : IDL.Func([IDL.Text], [IDL.Vec(Reaction)], ['query']),
  'getReadReceiptsEnabled' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  'getSentRequests' : IDL.Func([IDL.Text], [IDL.Vec(ConnectionRequest)], []),
  'getSnapScore' : IDL.Func([IDL.Text], [IDL.Nat], ['query']),
  'getStreak' : IDL.Func([IDL.Text, IDL.Text], [IDL.Nat], ['query']),
  'getUnreadCount' : IDL.Func([IDL.Text], [IDL.Nat], []),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isGhostMode' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  'login' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : UserProfile, 'err' : IDL.Text })],
      [],
    ),
  'loginWithII' : IDL.Func(
      [],
      [IDL.Variant({ 'ok' : UserProfile, 'err' : IDL.Text })],
      [],
    ),
  'markMessageRead' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'postStory' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'recordDailyLogin' : IDL.Func([IDL.Text], [IDL.Nat], []),
  'register' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : UserProfile, 'err' : IDL.Text })],
      [],
    ),
  'registerWithII' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : UserProfile, 'err' : IDL.Text })],
      [],
    ),
  'respondToRequest' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Bool],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'searchUsers' : IDL.Func([IDL.Text], [IDL.Vec(UserProfile)], ['query']),
  'sendCapsuleSnap' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Int],
      [IDL.Variant({ 'ok' : CapsuleMessage, 'err' : IDL.Text })],
      [],
    ),
  'sendConnectionRequest' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'sendGroupMessage' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : GroupMessage, 'err' : IDL.Text })],
      [],
    ),
  'sendMessage' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : Message, 'err' : IDL.Text })],
      [],
    ),
  'sendSnap' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Bool, IDL.Bool],
      [IDL.Variant({ 'ok' : Message, 'err' : IDL.Text })],
      [],
    ),
  'setGhostMode' : IDL.Func(
      [IDL.Text, IDL.Bool],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'setReadReceiptsEnabled' : IDL.Func(
      [IDL.Text, IDL.Bool],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'updateProfile' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'viewSnap' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const GroupInfo = IDL.Record({
    'id' : IDL.Text,
    'members' : IDL.Vec(IDL.Text),
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'createdBy' : IDL.Text,
  });
  const Badge = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'unlocked' : IDL.Bool,
    'description' : IDL.Text,
  });
  const UserProfile = IDL.Record({
    'bio' : IDL.Text,
    'username' : IDL.Text,
    'displayName' : IDL.Text,
    'createdAt' : IDL.Int,
    'principalText' : IDL.Text,
    'passwordHash' : IDL.Text,
  });
  const CapsuleMessage = IDL.Record({
    'id' : IDL.Text,
    'unlockAt' : IDL.Int,
    'receiverId' : IDL.Text,
    'timestamp' : IDL.Int,
    'blobId' : IDL.Text,
    'isUnlocked' : IDL.Bool,
    'senderId' : IDL.Text,
  });
  const Story = IDL.Record({
    'id' : IDL.Text,
    'authorUsername' : IDL.Text,
    'expiresAt' : IDL.Int,
    'timestamp' : IDL.Int,
    'caption' : IDL.Text,
    'blobId' : IDL.Text,
    'authorDisplayName' : IDL.Text,
  });
  const GroupMessage = IDL.Record({
    'id' : IDL.Text,
    'content' : IDL.Text,
    'senderUsername' : IDL.Text,
    'isSnap' : IDL.Bool,
    'groupId' : IDL.Text,
    'timestamp' : IDL.Int,
    'snapBlobId' : IDL.Opt(IDL.Text),
  });
  const LeaderboardEntry = IDL.Record({
    'username' : IDL.Text,
    'displayName' : IDL.Text,
    'rank' : IDL.Nat,
    'snapScore' : IDL.Nat,
  });
  const Message = IDL.Record({
    'id' : IDL.Text,
    'content' : IDL.Text,
    'isRead' : IDL.Bool,
    'isSnap' : IDL.Bool,
    'isEphemeral' : IDL.Bool,
    'receiverId' : IDL.Text,
    'timestamp' : IDL.Int,
    'snapBlobId' : IDL.Opt(IDL.Text),
    'senderId' : IDL.Text,
    'snapViewed' : IDL.Bool,
  });
  const ConnectionStatus = IDL.Variant({
    'pending' : IDL.Null,
    'accepted' : IDL.Null,
    'declined' : IDL.Null,
  });
  const ConnectionRequest = IDL.Record({
    'id' : IDL.Text,
    'status' : ConnectionStatus,
    'createdAt' : IDL.Int,
    'toUser' : IDL.Text,
    'fromUser' : IDL.Text,
  });
  const Reaction = IDL.Record({
    'username' : IDL.Text,
    'emoji' : IDL.Text,
    'timestamp' : IDL.Int,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addReaction' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'clearAllData' : IDL.Func([], [IDL.Variant({ 'ok' : IDL.Null })], []),
    'createGroup' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Vec(IDL.Text)],
        [IDL.Variant({ 'ok' : GroupInfo, 'err' : IDL.Text })],
        [],
      ),
    'deleteStory' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'getAchievements' : IDL.Func([IDL.Text], [IDL.Vec(Badge)], ['query']),
    'getAllUsers' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCapsuleMessages' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Vec(CapsuleMessage)],
        [],
      ),
    'getCapsuleStatus' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Opt(CapsuleMessage)],
        ['query'],
      ),
    'getConversations' : IDL.Func(
        [IDL.Text],
        [
          IDL.Vec(
            IDL.Record({
              'lastMessageContent' : IDL.Text,
              'lastMessageTimestamp' : IDL.Int,
              'username' : IDL.Text,
              'displayName' : IDL.Text,
              'unreadCount' : IDL.Nat,
            })
          ),
        ],
        [],
      ),
    'getFriendStories' : IDL.Func([IDL.Text], [IDL.Vec(Story)], []),
    'getFriends' : IDL.Func([IDL.Text], [IDL.Vec(UserProfile)], []),
    'getGroupMessages' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Int],
        [IDL.Vec(GroupMessage)],
        [],
      ),
    'getGroups' : IDL.Func([IDL.Text], [IDL.Vec(GroupInfo)], []),
    'getLeaderboard' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(LeaderboardEntry)],
        ['query'],
      ),
    'getMessages' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Int],
        [IDL.Vec(Message)],
        [],
      ),
    'getPendingRequestCount' : IDL.Func([IDL.Text], [IDL.Nat], []),
    'getPendingRequests' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(ConnectionRequest)],
        [],
      ),
    'getProfile' : IDL.Func([IDL.Text], [IDL.Opt(UserProfile)], ['query']),
    'getReactions' : IDL.Func([IDL.Text], [IDL.Vec(Reaction)], ['query']),
    'getReadReceiptsEnabled' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
    'getSentRequests' : IDL.Func([IDL.Text], [IDL.Vec(ConnectionRequest)], []),
    'getSnapScore' : IDL.Func([IDL.Text], [IDL.Nat], ['query']),
    'getStreak' : IDL.Func([IDL.Text, IDL.Text], [IDL.Nat], ['query']),
    'getUnreadCount' : IDL.Func([IDL.Text], [IDL.Nat], []),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isGhostMode' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
    'login' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : UserProfile, 'err' : IDL.Text })],
        [],
      ),
    'loginWithII' : IDL.Func(
        [],
        [IDL.Variant({ 'ok' : UserProfile, 'err' : IDL.Text })],
        [],
      ),
    'markMessageRead' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'postStory' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'recordDailyLogin' : IDL.Func([IDL.Text], [IDL.Nat], []),
    'register' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : UserProfile, 'err' : IDL.Text })],
        [],
      ),
    'registerWithII' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : UserProfile, 'err' : IDL.Text })],
        [],
      ),
    'respondToRequest' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Bool],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'searchUsers' : IDL.Func([IDL.Text], [IDL.Vec(UserProfile)], ['query']),
    'sendCapsuleSnap' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Int],
        [IDL.Variant({ 'ok' : CapsuleMessage, 'err' : IDL.Text })],
        [],
      ),
    'sendConnectionRequest' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'sendGroupMessage' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : GroupMessage, 'err' : IDL.Text })],
        [],
      ),
    'sendMessage' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : Message, 'err' : IDL.Text })],
        [],
      ),
    'sendSnap' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Bool, IDL.Bool],
        [IDL.Variant({ 'ok' : Message, 'err' : IDL.Text })],
        [],
      ),
    'setGhostMode' : IDL.Func(
        [IDL.Text, IDL.Bool],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'setReadReceiptsEnabled' : IDL.Func(
        [IDL.Text, IDL.Bool],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'updateProfile' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'viewSnap' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };