/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export type { UserProfile, ConnectionRequest, Message, ConversationEntry } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface backendInterface {
    _initializeAccessControlWithSecret(secret: string): Promise<void>;
    register(username: string, password: string, displayName: string): Promise<{ ok: any } | { err: string }>;
    login(username: string, password: string): Promise<{ ok: any } | { err: string }>;
    loginWithII(): Promise<{ ok: any } | { err: string }>;
    registerWithII(username: string, displayName: string): Promise<{ ok: any } | { err: string }>;
    getProfile(username: string): Promise<any[]>;
    updateProfile(displayName: string, bio: string): Promise<{ ok: null } | { err: string }>;
    searchUsers(q: string): Promise<any[]>;
    sendConnectionRequest(toUsername: string): Promise<{ ok: null } | { err: string }>;
    respondToRequest(requestId: string, accept: boolean): Promise<{ ok: null } | { err: string }>;
    getPendingRequests(): Promise<any[]>;
    getFriends(): Promise<any[]>;
    sendMessage(toUsername: string, content: string): Promise<{ ok: any } | { err: string }>;
    sendSnap(toUsername: string, blobId: string, isEphemeral: boolean, saveToChat: boolean): Promise<{ ok: any } | { err: string }>;
    getMessages(withUsername: string, since: bigint): Promise<any[]>;
    markMessageRead(messageId: string): Promise<{ ok: null } | { err: string }>;
    viewSnap(messageId: string): Promise<{ ok: null } | { err: string }>;
    getUnreadCount(): Promise<bigint>;
    getPendingRequestCount(): Promise<bigint>;
    getConversations(): Promise<any[]>;
}
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(_secret: string): Promise<void> {}
    async register(username: string, password: string, displayName: string): Promise<{ ok: any } | { err: string }> {
        try {
            return await (this.actor as any).register(username, password, displayName);
        } catch(e) { if (this.processError) this.processError(e); throw e; }
    }
    async login(username: string, password: string): Promise<{ ok: any } | { err: string }> {
        try {
            return await (this.actor as any).login(username, password);
        } catch(e) { if (this.processError) this.processError(e); throw e; }
    }
    async loginWithII(): Promise<{ ok: any } | { err: string }> {
        try {
            return await (this.actor as any).loginWithII();
        } catch(e) { if (this.processError) this.processError(e); throw e; }
    }
    async registerWithII(username: string, displayName: string): Promise<{ ok: any } | { err: string }> {
        try {
            return await (this.actor as any).registerWithII(username, displayName);
        } catch(e) { if (this.processError) this.processError(e); throw e; }
    }
    async getProfile(username: string): Promise<any[]> {
        try {
            return await (this.actor as any).getProfile(username);
        } catch(e) { if (this.processError) this.processError(e); throw e; }
    }
    async updateProfile(displayName: string, bio: string): Promise<{ ok: null } | { err: string }> {
        try {
            return await (this.actor as any).updateProfile(displayName, bio);
        } catch(e) { if (this.processError) this.processError(e); throw e; }
    }
    async searchUsers(q: string): Promise<any[]> {
        try {
            return await (this.actor as any).searchUsers(q);
        } catch(e) { if (this.processError) this.processError(e); throw e; }
    }
    async sendConnectionRequest(toUsername: string): Promise<{ ok: null } | { err: string }> {
        try {
            return await (this.actor as any).sendConnectionRequest(toUsername);
        } catch(e) { if (this.processError) this.processError(e); throw e; }
    }
    async respondToRequest(requestId: string, accept: boolean): Promise<{ ok: null } | { err: string }> {
        try {
            return await (this.actor as any).respondToRequest(requestId, accept);
        } catch(e) { if (this.processError) this.processError(e); throw e; }
    }
    async getPendingRequests(): Promise<any[]> {
        try {
            return await (this.actor as any).getPendingRequests();
        } catch(e) { if (this.processError) this.processError(e); throw e; }
    }
    async getFriends(): Promise<any[]> {
        try {
            return await (this.actor as any).getFriends();
        } catch(e) { if (this.processError) this.processError(e); throw e; }
    }
    async sendMessage(toUsername: string, content: string): Promise<{ ok: any } | { err: string }> {
        try {
            return await (this.actor as any).sendMessage(toUsername, content);
        } catch(e) { if (this.processError) this.processError(e); throw e; }
    }
    async sendSnap(toUsername: string, blobId: string, isEphemeral: boolean, saveToChat: boolean): Promise<{ ok: any } | { err: string }> {
        try {
            return await (this.actor as any).sendSnap(toUsername, blobId, isEphemeral, saveToChat);
        } catch(e) { if (this.processError) this.processError(e); throw e; }
    }
    async getMessages(withUsername: string, since: bigint): Promise<any[]> {
        try {
            return await (this.actor as any).getMessages(withUsername, since);
        } catch(e) { if (this.processError) this.processError(e); throw e; }
    }
    async markMessageRead(messageId: string): Promise<{ ok: null } | { err: string }> {
        try {
            return await (this.actor as any).markMessageRead(messageId);
        } catch(e) { if (this.processError) this.processError(e); throw e; }
    }
    async viewSnap(messageId: string): Promise<{ ok: null } | { err: string }> {
        try {
            return await (this.actor as any).viewSnap(messageId);
        } catch(e) { if (this.processError) this.processError(e); throw e; }
    }
    async getUnreadCount(): Promise<bigint> {
        try {
            return await (this.actor as any).getUnreadCount();
        } catch(e) { if (this.processError) this.processError(e); throw e; }
    }
    async getPendingRequestCount(): Promise<bigint> {
        try {
            return await (this.actor as any).getPendingRequestCount();
        } catch(e) { if (this.processError) this.processError(e); throw e; }
    }
    async getConversations(): Promise<any[]> {
        try {
            return await (this.actor as any).getConversations();
        } catch(e) { if (this.processError) this.processError(e); throw e; }
    }
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
